set -g base-index 1

# status bar
set -g status-style fg=white,bg=#0e1419,bold
set -g status-left-style fg=green
set -g status-right-style fg=blue
set -g status-justify centre

# colors
# set -g mode-style fg=white,bg=cyan,bold
set -g message-style fg=white,bg=magenta,bold
# copy/paste
set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy -in -selection clipboard'

# prefix + bindings
bind-key -r f run-shell "tmux neww tmux-sessionizer"
bind r source-file ~/.tmux.conf
bind-key -r h run-shell "tmux split-window -l 80 -h bash -c cht.sh"
